import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import StarsCanvas from "./components/Stars";

const inter = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} w-screen h-screen bg-gradient-to-r from-green-400 to-purple-700 flex justify-center items-center`}
      >
        <main className="overflow-hidden bg-black w-full max-w-[1100px] h-full sm:max-h-[600px] lg:max-h-[550px] text-white">
          <Navbar />
          <StarsCanvas />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
